### ISSUE TITLE
Plans for v0.0.1

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/WebGL4J#2]
This is the tracker issue for the release of v0.0.1. Here are the things I think there should be in the repo before the release should be done.
- [x] Complete the `WebGL10` class constants and methods.
- [x] A utility class for polling high precision timing.
- [x] Several examples and demos in separate projects.
- [x] Ability to change the active context at runtime, support rendering on multiple canvases.
- [x] Fullscreen context support
- [ ] ~~A math util library? (Thinking about [JOML](https://github.com/JOML-CI/JOML/issues/45), but it has no GWT support right now).~~ (Postponed to version 0.1.1)
- [ ] ~~Resource loading comfort methods (loading textures, etc.,)~~ (Postponed to version 0.1.1)

**Comment by sriharshachilakapati** [comment]
Since most of the planned things are now done, I'll be closing this tracker once I get to document all the methods and classes written till now.

**Comment by sriharshachilakapati** [comment]
Version 0.0.1a has been released: https://github.com/sriharshachilakapati/WebGL4J/releases/tag/v0.0.1
