### ISSUE TITLE
Plans for v0.1.1

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/WebGL4J#3]
- [x] WebGL20 class constants and methods
- [x] Add `@WebGLContext.HandlesContextLost` annotation
- [x] Use generics for methods which returns value of multiple data types
- [x] Complete documentation for `WebGLContext`
- [x] JOML-GWT (planned at 0.0.1, and is being worked on a fork of JOML)
