### ISSUE TITLE
Plans for v0.2.4

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/WebGL4J#4]
The plans for v0.2.1 are to add all the non-draft WebGL extensions that are written against the WebGL 1.0 specification. Those include the following.
- [x] ANGLE_instanced_arrays
- [x] EXT_blend_minmax
- [x] EXT_frag_depth
- [x] EXT_shader_texture_lod
- [x] EXT_texture_filter_anisotropic
- [x] OES_element_index_uint
- [x] OES_standard_derivatives
- [x] OES_texture_float
- [x] OES_texture_float_linear
- [x] OES_texture_half_float
- [x] OES_texture_half_float_linear
- [x] OES_vertex_array_object
- [x] WEBGL_compressed_texture_s3tc
- [x] WEBGL_debug_renderer_info
- [x] WEBGL_debug_shaders
- [x] WEBGL_depth_texture
- [x] WEBGL_draw_buffers
- [x] WEBGL_lose_context

These extensions does not include the community approved extensions.
